### ISSUE TITLE
Dashboard take too long start

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/memex-explorer#119]
We are currently not displaying any plots with frontierpages.csv data, but we still depend on that file existing and having data for the dashboard page to display. The frontierpages file takes a long time to be generated (~10min, on a test). I tried removing the frontierpages.csv dependency on the code, but was still getting an error.

The ultimate solution probably involves digging into the ACHE code and providing a better output, a streaming API instead of a bulk write to files every X seconds. For now remove frontier pages dependency.

**Comment by kdodia** [comment]
Removed in #177
