### ISSUE TITLE
Better UI for selecting an icon in `add project`

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/memex-explorer#238]
Improve UI by selecting an icon instead of writing the icon name

![screen shot 2015-01-08 at 2 35 40 pm](https://cloud.githubusercontent.com/assets/4940549/5670234/ba2263a4-9743-11e4-984d-6e62a7ac3e5e.png)

**Comment by brittainhard** [comment]
Closing. We are no longer using icons.
