### ISSUE TITLE
Django based architecture that allows for registering microservices

### ISSUE THREAD

**Issue by aterrel** [ContinuumIO/memex-explorer#291]
- [x] Basic structure of django applications
- [x] Start projects, configure, register apps

**Comment by brittainhard** [comment]
Project is more or less completed. Moving onto crawls tomorrow.

**Comment by kdodia** [comment]
Yes. Microservice Integration guide [here](https://github.com/ContinuumIO/memex-explorer/wiki/Microservice-Integration).
