### ISSUE TITLE
Revert to python 2.7?

### ISSUE THREAD

**Issue by brittainhard** [ContinuumIO/memex-explorer#336]
Scrapy uses Twisted, which is incompatable with python 3. Should we downgrade to python 2.7 in order to be able to use Scrapy?

http://doc.scrapy.org/en/0.24/faq.html#what-python-versions-does-scrapy-support

**Comment by aterrel** [comment]
Let's wait until next sprint for this discussion.

**Comment by aterrel** [comment]
Okay @chdoig points out that if we don't push to py2.7 then every app we work with has to be py2.7. So let's actually port back to py27.

**Comment by brittainhard** [comment]
Done.
